### ISSUE TITLE
What to do when (Channel.canReceiveTransaction(Transaction) == false)

### ISSUE THREAD

**Issue by aamnony** [amnonya/OOP_046271#1]
https://github.com/amnonya/OOP_046271/blob/75be56c12fd8cfcf383375c1e3d0ab8de4a340e9/homework2/SimulatorTestDriver.java#L92

Maybe throw an exception?

**Comment by ezsushy** [comment]
Don't think there is a need.

According to the exercise we just wait for the next step to pass the
transaction if the channel is full.

**Comment by aamnony** [comment]
Okay, so can close this and remove TODO (and comment) from code
